klaudiosinani/signale

- signale.js
This PR provides a mechanism for providing a writable stream to a Signale instance. The most common use would be to pass `process.stdout` instead of the default `process.stderr` although you could do other things like write to a socket if your client can understand ANSI escape sequences.
> configureable stream defaulting to process.stdout

- contributing.md
Super tiny PR! Just fixing a link in the contributing guide 🔧 🔗 😸
> Fix link to "help wanted" label inside the contributing guide

- signale.js
- types.js
This would allow you to pass a stream as a property when configuring types to use that stream over the default one. 
This does add a property to types that in its current state could not be represented by the config in package.json. If you feel this is necessary I can change it that type.stream is stream identifier and then have an api-only option of a map of identifier to implementation.
If you are happy with the current implementation I will crack on with updating the documentation.
Also, love the library in both functionality and ease of contribution!
EDIT: This now also fixes #26 by providing the ability to have an array of streams as either `options.stream` or `type.stream`
> Added support for multiple streams & optional streams per logger. Fixes #26

- signale.js
This PR enables the selective override of user-specified attributes on the default loggers, by deep merging the custom logger types against the default ones, and preserving the values of all unmodified attributes, e.g:
```js
// example.js
const {Signale} = require('signale');
const options = {
types: {
error: {
// Here `yellow` will override only the default `red` color 
// and all other default attributes will stay unmodified
color: 'yellow'
}
}
};
const signale = new Signale(options);
console.log(signale._types);
```
The `error` type logger will now hold the following expected attributes:
```js
{
// ...
error: {
badge: '✖',
color: 'yellow',
label: 'error'
},
// ...
}
```
Currently, `error` receives only the color attribute, losing all other default ones:
```js
{
// ...
error: {
color: …
```
> Enabled deep-merging between default & custom types

- signale.js
Fixes https://github.com/klauscfhq/signale/issues/5 by ensuring we only call path.basename on callsites with a valid file path. The find below should act as a filter of these falsy (usually null from what I've seen) values.
In the unlikely case that there is no suitable file path, set the filename as unknown.
> fix: handle anonymous callsites. (fixes #5)

- signale.js
This PR addresses the problem described in https://github.com/klauscfhq/signale/issues/34
When trying to log an Error with an undefined stack trace, now `signale` correctly logs the error name and ignores the `stack` property.
Before:
```
const [name, ...rest] = msg.stack.split('\n');
^
TypeError: Cannot read property 'split' of undefined
```
After:
```
✖  error     SyntaxError
```
> Check if Error object has stack property. Fixes #34.

- signale.js
Add a _padSpace method instead of padEnd. Fixes #46
> Add a _padSpace method instead of padEnd. Fixes #46

- readme.md
- signale.js
Adds the ability to check  whether the logging functionality of a specific `Signale` instance is enabled, by utilizing the `isEnabled()` method:
```js
const signale = require('signale');
signale.success('foo');
//=> ✔  success  foo
signale.isEnabled();
// => true
signale.disable();
signale.success('foo');
//=>
signale.isEnabled();
// => false
```
- Exported `isEnabled()` as an API method. https://github.com/klauscfhq/signale/commit/b3454e1533d5afe0376cddc827a698274487b748
- Updated documentation. https://github.com/klauscfhq/signale/commit/5f7b6ff088ffbfe5512324aa56ce70fd3b231e05
> Add `isEnabled()` API Method for Logger Enablement Check

- types.js
Due to the fact that `await` is a reserved keyword used exclusively under the scope of async functions, a new `wait` type logger is introduced by this PR, which will act as an alias/alternative. The main purpose for this addition is for the API to be in sync with the best possible practices design-wise and to prevent any possible inconveniences, _(not actual parsing or runtime errors)_, resulting from the usage a function named `await`, such as code linting errors, confusion during debugging or auditing etc. 
```js
// example.js
const {await} = require('signale');
await('Executing calculation...');
// Possible linting error: 'Can not use keyword await outside an async function'
```
The existing `await` logger will not be removed from the API for backwards compatibility reasons, but its …
> Added new `wait` alias for `await` logger

- readme.md
> fix repo badge pointing to old legacy repo

- signale.js
The PR introduces the ability to filter out secrets/sensitive-info from the body & metadata, i.e. scope name etc, of to-be-logged messages. The feature can be utilized through the `secrets` option, which is part of the configuration object passed to a `Signale` instance on initialization. The option is of type `Array<String|Number>` and can hold multiple secrets, all of which are removed, if present, from the to-be-logged messages and replaced with the default `'[secure]'` string. Additionally, when the unary `signale.scope(name)` function is used, the returned `Signale` instance inherits all the secrets belonging to its parent. The secrets checking process is performed in a **case-sensitive** manner. Finally, this PR is a follow-up to #71.
It is **critical** and **highly recommended** to …
> Add support for secrets/sensitive-info filtering

- readme.md
Updates the documentation regarding the secrets filtering feature, as presented on #78.
> Docs: Update documentation on secrets filtering

- signale.js
- types.js
The PR introduces the ability to display/hide logged messages through a scaled logging level system. The logging level can be defined through the `logLevel` option, which is of type `String` & it is part of the configuration object pass to the initialization of a `Signale` instance, and can be one of the following 5 strings:
- `'info'` - Displays all the messages of all logger types.
- `'timer'` - Displays only the messages of `time`, `timeEnd`, `debug`, `warn`, `error` & `fatal` logger types.
- `'debug'` - Displays only the messages of `debug`, `warn`, `error` & `fatal` logger types.
- `'warn'` - Displays only the messages of `warn`, `error` & `fatal` logger types.
- `'error'` - Displays only the messages of `error` & `fatal` logger types.
The **default** value is `'info'` for the …
> Add support for log levels. Fixes #51

- readme.md
Updates the documentation regarding the log levels feature, as presented on #80.
> Docs: Update documentation regarding log levels

- signale.js
The PR restricts the use of the **interactive mode** only on [`tty.WriteStream`](https://nodejs.org/api/tty.html#tty_class_tty_writestream) writable streams, due to the fact that the following functions, that are utilized by the mode, are unavailable on non-TTY writables, i.e. `fs.WriteStream` streams, IDE consoles etc:
- [`writeStream.clearLine(dir)`](https://nodejs.org/api/tty.html#tty_writestream_clearline_dir)
- [`writeStream.cursorTo(x, y)`](https://nodejs.org/api/tty.html#tty_writestream_cursorto_x_y)
- [`writeStream.moveCursor(dx, dy)`](https://nodejs.org/api/tty.html#tty_writestream_movecursor_dx_dy)
In the future, the above-described methods will be employed through the [`readline`](https://nodejs.org/api/readline.html#readline_readline) module API instead of the currently used …
> Enable interactive mode only on `tty.WriteStream` streams. Fixes #55

- signale.js
The PR replaces the function of **Group A**, originating from the [`tty.WriteStream`](https://nodejs.org/api/tty.html#tty_class_tty_writestream) API, which are used by the **interactive mode**, with the ones of **Group B**, originating from the  [`readline`](https://nodejs.org/api/readline.html#readline_readline) API, due to the [**deprecated nature**](https://github.com/nodejs/node/blob/master/lib/tty.js#L129) of the ones in the first group. 
- [`writeStream.clearLine(dir)`](https://nodejs.org/api/tty.html#tty_writestream_clearline_dir)
- [`writeStream.cursorTo(x, y)`](https://nodejs.org/api/tty.html#tty_writestream_cursorto_x_y)
- [`writeStream.moveCursor(dx, dy)`](https://nodejs.org/api/tty.html#tty_writestream_movecursor_dx_dy)
- [`readline.clearLine(stream, …
> Replace interactive mode `tty` API with `readline` (#82)

- types/signale.d.ts
The PR, a follow-up to #85, introduces the missing TS ambient type declaration for the Signale API.
- `addSecrets(secrets)`
- `clearSecrets()`
- `config(configObj)`
- `disable()`
- `enable()`
- `isEnabled()`
Additionally, adds the following 3 types to the exported `signale` namespace: 
- `ChalkColor`
- `Secret`
- `LogLevel`
> TypeScript: Included missing ambient type declarations

- package.json
- test/config.ts
- test/custom.ts
- test/default.ts
- test/override.ts
- test/scoped.ts
- test/secrets.ts
- test/streams.ts
- test/timers.ts
- test/tsconfig.json
The PR, a follow-up to #86 and #85, introduces TS ambient type declaration tests as well as new minimal `tsconfig.json` set-up. The testing process can be initialized through the newly added `test:ts` script.
> TypeScript: Added ambient type declaration tests

- src/signale.js
The PR normalized the appearance of dates, utilized through the `displayDate` option, to the following global format:
- `YYYY-MM-DD`
> Normalize date format of `displayDate` option. Fixes #88 (#84)

- src/signale.js
The PR normalized the appearance of timestamps, utilized through the `displayTimestamp` option, to the following global format:
- `HH:MM:SS`
> Normalize time format of `displayTimestamp` option. Fixes #89 (#84)
